### ISSUE TITLE
Изменение структуры проекта

### ISSUE THREAD

**Issue by vdsimako** [andrey17895/SpringTest#10]
- Разнести по пакетам объекты, относящиеся к har'у и объекты относящиеся к тестовому профилю

- Снести все классы(dto, entity, exception) в пакет model

- Интерфейсы именовать начиная с I(IHarParserService)

- Снести реализацию классов в один проаннотированные `@Configuration`

- Возвращать Collection вместо Iterable

- Раз классы dto имеют суффикс Dto, то у entity суффикс Entity можно убрать

**Comment by andrey17895** [comment]
>     * Снести реализацию классов в один проаннотированные `@Configuration`
Не понял что ты имеешь в ввиду
