### ISSUE TITLE
Унифицировать настройки приложения

### ISSUE THREAD

**Issue by vdsimako** [andrey17895/SpringTest#2]

**Comment by andrey17895** [comment]
Перенес все настройки в application.yml

**Comment by vdsimako** [comment]
где?
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/15703327/69228894-78075300-0b95-11ea-8546-b222c4fe1937.png">

**Comment by andrey17895** [comment]
Теперь точно поменял)
![image](https://user-images.githubusercontent.com/25550745/69240870-7e55f900-0bae-11ea-9a94-029c0d6a1f91.png)
